version: '3.8'
services:
  api:
    build: ./server
    restart: unless-stopped
    env_file:
      - ./server/.env.example
    depends_on:
      - mongo
      - redis
    ports:
      - "4000:4000"
    networks:
      - mern-net
  mongo:
    image: mongo:6.0
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-net
  redis:
    image: redis:7
    networks:
      - mern-net
  nginx:
    image: nginx:stable
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - mern-net

volumes:
  mongo-data:

networks:
  mern-net:
