apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mern-api
  template:
    metadata:
      labels:
        app: mern-api
    spec:
      containers:
        - name: api
          image: mern-ascent-api:latest
          ports:
            - containerPort: 4000
          env:
            - name: MONGO_URI
              value: "mongodb://mongo:27017/mern_ascent"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: mern-secrets
                  key: jwt
          readinessProbe:
            httpGet:
              path: /healthz
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 4000
            initialDelaySeconds: 15
            periodSeconds: 20
